apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-framework
  labels:
    app: tracing-framework
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: tracing-framework
  template:
    metadata:
      labels:
        app: tracing-framework
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: tracing-framework
          image: tracing-framework:0.0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
          env:
            - name: MONGO_URL
              value: "mongodb://tracing-db-service:27017"
            - name: MONGO_DATABASE
              value: "tracing-db"
            - name: PORT
              value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-framework
  labels:
    app: tracing-framework
  namespace: istio-system
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: tracing-framework
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: proxy-config
  namespace: istio-system
spec:
  tracing:
    - randomSamplingPercentage: 100.00
    - providers:
        - name: tracing-provider