# Persistent Volume Chain for MongoDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tracing-db-pvc
  namespace: istio-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-db
  labels:
    app: tracing-db
  namespace: istio-system
spec:
  selector:
    matchLabels:
      app: tracing-db
  template:
    metadata:
      labels:
        app: tracing-db
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - image: mongo
          name: mongo
          ports:
            - containerPort: 27017
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: tracing-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-db-service
  labels:
    run: tracing-db-service
  namespace: istio-system
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: tracing-db