apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    enableTracing: true
    extensionProviders:
      - name: tracing-provider
        zipkin:
          service: tracing-framework.istio-system.svc.cluster.local
          port: 8080