apiVersion: apps/v1
kind: Deployment
metadata:
  name: tracing-framework
  namespace: istio-system
  labels:
    app: tracing-framework
spec:
  selector:
    matchLabels:
      app: tracing-framework
  template:
    metadata:
      labels:
        app: tracing-framework
        sidecar.istio.io/inject: "false"
    spec:
      containers:
        - name: tracing-framework
          image: tracing-app:0.0.1
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
          env:
            - name: MONGO_URL
              value: mongodb://10.244.0.93:27017
---
apiVersion: v1
kind: Service
metadata:
  name: tracing-framework
  namespace: istio-system
  labels:
    app: tracing-framework
spec:
  type: ClusterIP
  ports:
    - name: http-query
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: tracing-framework
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: zipkin
  name: zipkin
  namespace: istio-system
spec:
  ports:
    - port: 9411
      targetPort: 8080
      name: http-query
  selector:
    app: tracing-framework